### ISSUE TITLE
Unsupported version of chain snapshot: 2. 

### ISSUE THREAD

**Issue by ArayofEntropy** [EOS-Jungle-Testnet/Node-Manual-Installation#3]
My nodeos version is v1.7.3
When I startup the nodeos with jungle network snapshot ,I got the error below:

```
info  2019-05-12T10:45:17.465 thread-0  controller.cpp:1732           startup              ] Starting initialization from snapshot, this may take a significant amount of time
error 2019-05-12T10:45:17.595 thread-0  main.cpp:121                  main                 ] 3240001 snapshot_validation_exception: Snapshot Validation Exception
Unsupported version of chain snapshot: 2. Supported version must be between 1 and 1 inclusive.
    {"version":2,"min":1,"max":1}
    thread-0  chain_snapshot.hpp:28 validate

    {}
    thread-0  chain_plugin.cpp:731 plugin_startup
```

Is there anything upgraded？ Since I never meet this problem before. How is snapshot be the version 2 now?

Could anybody help me please?

**Comment by bublik77** [comment]
> My nodeos version is v1.7.3
> When I startup the nodeos with jungle network snapshot ,I got the error below:
> 
> ```
> info  2019-05-12T10:45:17.465 thread-0  controller.cpp:1732           startup              ] Starting initialization from snapshot, this may take a significant amount of time
> error 2019-05-12T10:45:17.595 thread-0  main.cpp:121                  main                 ] 3240001 snapshot_validation_exception: Snapshot Validation Exception
> Unsupported version of chain snapshot: 2. Supported version must be between 1 and 1 inclusive.
>     {"version":2,"min":1,"max":1}
>     thread-0  chain_snapshot.hpp:28 validate
> 
>     {}
>     thread-0  chain_plugin.cpp:731 plugin_startup
> ```
> 
> Is there anything upgraded？ Since I never meet this problem before. How is snapshot be the version 2 now?
> 
> Could anybody help me please?

Hello,
Jungle Testnet Consensus protocol upgrade has happened. All nodes should be upgraded to v1.8.0-rc1 to work correctly. This upgrade requires full chain replay.
