### ISSUE TITLE
Unable to continue syncing at this time

### ISSUE THREAD

**Issue by YasserNoureldin** [EOS-Jungle-Testnet/Node-Manual-Installation#5]
I am running a Jungle Testnet EOS node on my server with manual installation and it keeps syncing till i reach _"last_irreversible_block_num":28031875_, the it stops syncing.

by checking the stderr.log file, this is what i get :

_"
request_next_chunk   ] Unable to continue syncing at this time
set_state            ] old state lib catchup becoming in sync
"_

and this is the EOS server version i am currently running: _v2.0.0-e19afc8072219282a7c3fc20e47aa80cb70299e4_

Any help how to continue syncing new blocks to my node?

Thanks.

**Comment by bublik77** [comment]
Hi,
We are very sorry, we should have written about that but it is an issue with bad block and sync not work from the begin, try to use the snapshot or blocks and state from the backup  http://backup.cryptolions.io/Jungle/  and start your node
in near the future, there will be Jungle3, we are work on this

**Comment by YasserNoureldin** [comment]
Hello,
I downloaded blocks and added it instead of the existing blocks folder, but now when i try to run the node i get this error: 

 _producer_double_confirm: Producer is double confirming known range
producer jungleswedem double-confirming known range_

couldn't find a solution for this.

Thanks.

**Comment by bublik77** [comment]
Hello,
I need to check it

**Comment by bublik77** [comment]
Hello,
Sorry for the delayed answer
I  have launched from the backup without any error,
did you copy both block and state?

**Comment by YasserNoureldin** [comment]
Hi,
i copied the blocks, and for the state .. the existing state folder have there files:

code_cache.bin  
fork_db.dat  
shared_memory.bin

and the downloaded state history from the link and this are the extracted files:

chain_state_history.index  
chain_state_history.log  
trace_history.index  
trace_history.log

so i just add the new files to the existing and the same state folder?

**Comment by bublik77** [comment]
better replace both folders

**Comment by YasserNoureldin** [comment]
Unfortunately i still get the same error: 

_error: producer_double_confirm: Producer is double confirming known range
producer jungleswedem double-confirming known range
    {"prod":"jungleswedem","num":28032198,"confirmed":1,"last_produced":28032197}_

**Comment by bublik77** [comment]
but you run your node whether it stops immediately  

> Hi,
> i copied the blocks, and for the state .. the existing state folder have there files:
> 
> code_cache.bin
> fork_db.dat
> shared_memory.bin
> 
> and the downloaded state history from the link and this are the extracted files:
> 
> chain_state_history.index
> chain_state_history.log
> trace_history.index
> trace_history.log
> 
> so i just add the new files to the existing and the same state folder?

no, 
state history have separate directory state-history and it is needed when you enable state history in the config file, directory tree looks like that 
```
blocks/
├── blocks.index
├── blocks.log
└── reversible
    └── shared_memory.bin
state/
├── code_cache.bin
└── shared_memory.bin
state-history/
├── chain_state_history.index
├── chain_state_history.log
├── trace_history.index
└── trace_history.log
```
it is with enabled  state-history plugin

**Comment by YasserNoureldin** [comment]
Got it working perfectly now :) .. just disabled the state history and used the blocks and state folders.

Thanks.
